### ISSUE TITLE
umisteni lidi v hemicyclu

### ISSUE THREAD

**Issue by michalskop** [michalskop/hlasovali.cz#14]
Feedback: "Škoda, že ti radní pořád nesedí na stejným místě, ale přesouvají se na jednu nebo druhou stranu, podle toho, jak hlasovali. Bylo by to přehlednější a člověk by nemusel při každým hlasování prohlížet, kdo je kde. Úplně by stačily zelený/červený hvězdičky."

**Comment by OndrejPlachy** [comment]
Jak vyřešit označení zastupitelů, kteří byli nepřítomní? Nechat je ve výsledném obrázku s těmi, kteří hlasovali proti (tj. s červenýma hvězdičkama) nebo jim dát jinou hvězdičku, případně je udělat transparentní? + jejich pozice? přesunout nebo nechat na původním místě (viz předchozí koment).

**Comment by michalskop** [comment]
přemístěno do #19
duplicate of #19
