### ISSUE TITLE
řazení zastupitelů při zadávání

### ISSUE THREAD

**Issue by michalskop** [michalskop/hlasovali.cz#17]
razeni zastupitelu podle stran je v Olomouci na nic, bylo by lepsi kdyby se zobrazovali tak, jak jsem je tam zadal.

**Comment by OndrejPlachy** [comment]
http://www.olomouc.eu/administrace/repository/gallery/articles/19_/19346/012-zmo-20161017-hlasovani.cs.pdf

**Comment by michalskop** [comment]
Brno: "Navrhujeme přidat k jednotlivým zastupitelům nějaké pořadové číslo, podle kterého by se třídil seznam zastupitelů. Důvodem je odlišnost pořadí politických stran a zastupitelů v aplikaci a našeho hlasování. Při pořizování se pak  "listuje" a hledá správný zastupitel. Pak to musí naplňovat dva lidé, kdy jeden čte a druhý to zapisuje. Pokud by nám to naplňoval nějaký brigádník, tak by bylo určitě lepší, aby si to mohl třídit podle našeho setřídění."
