### ISSUE TITLE
FA ikony nefungují

### ISSUE THREAD

**Issue by davidindra** [michalskop/hlasovali.cz#20]
Zdravím,
na celém webu nefungují FontAwesome ikonky. Tady je chyba z Devtools:
`Access to Font at 'https://hlasovali.cz/fonts/fontawesome-webfont.ttf?v=4.6.3' from origin 'http://hlasovali.cz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hlasovali.cz' is therefore not allowed access.`
Vyřešilo by to vynucení HTTPS pro celý web, to by podle mne bylo i rozumné, případně nastavení dané hlavičky přes mod_headers v Apache.

**Comment by michalskop** [comment]
note: http by mělo rovnou přesměrovávat na https verzi

**Comment by michalskop** [comment]
opraveno v /etc/apache2/sites-available/hlasovali.cz.conf a v https://gist.github.com/michalskop/9edee4757545c7d905c4
